name: managed9
recipe: drupal9
config:
  php: '8.0'
  via: nginx
  webroot: docroot
  drush: false
  xdebug: false
services:
  appserver:
    build:
      - composer install
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver