image: proboci/ubuntu:18.04-php7.4
assets:
  - drupal9.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 9
    database: drupal9.sql.gz
    databaseGzipped: true
    clearCaches: false
    databaseUpdates: false
    subDirectory: docroot
  - name: Run composer install
    command: "composer install --working-dir=$SRC_DIR"
  - name: Use custom drush
    command: 'mv /usr/local/bin/drush /usr/local/bin/drush8; ln -s /src/vendor/drush/drush/drush /usr/local/bin/drush; chmod +x /src/vendor/drush/drush/drush'
  - name: Run database update
    command: "drush --root=$SRC_DIR/docroot/ updb -y"
  #- name: Sanitize database
  #  command: "drush --root=$SRC_DIR/docroot/ sqlsan -y"
  - name: Import config
    command: "drush --root=$SRC_DIR/docroot/ cim --source=$SRC_DIR/config/default -y"
  - name: Fix file permissions
    command: 'mkdir $SRC_DIR/docroot/sites/default/files/private && chown -R www-data:www-data $SRC_DIR/docroot/sites/default/files'
  #- name: Enable stage file proxy
  #  command: "drush --root=$SRC_DIR/docroot/ en stage_file_proxy -y && drush --root=$SRC_DIR/docroot/ cset stage_file_proxy.settings origin https://example.com -y"
  - name: Cache clear
    command: "drush --root=$SRC_DIR/docroot/ cr"